slug: planefence
url: https://github.com/MaxWinterstein/homeassistant-addons/
# image: ghcr.io/maxwinterstein/homeassistant-planefence-{arch}
version: 0.1.6
arch:
  - aarch64
  - amd64
description: Track aircraft flying near your ADS-B receiver with noise logging and alerts
hassio_api: true
homeassistant_api: true
map:
  - addon_config:rw
ingress: true
ingress_port: 80
init: false
name: Planefence
panel_icon: mdi:airplane-alert
panel_title: Planefence

options:
  PF_SOCK30003HOST: adsb-multi-portal-feeder
  PF_SOCK30003PORT: 30003
  PF_LAT: HOMEASSISTANT_LATITUDE
  PF_LON: HOMEASSISTANT_LONGITUDE
  PF_MAXDIST: 50
  PF_MAXALT: 10000
  TZ: UTC

schema:
  PF_SOCK30003HOST: str
  PF_SOCK30003PORT: port
  PF_LAT: match([+-]?(([1-9][0-9]*)|(0))([.,][0-9]+)?|HOMEASSISTANT_LATITUDE)?
  PF_LON: match([+-]?(([1-9][0-9]*)|(0))([.,][0-9]+)?|HOMEASSISTANT_LONGITUDE)?
  PF_MAXDIST: int
  PF_MAXALT: int
  TZ: str
  PA_DISCORD: url?
  PA_MASTODON_SERVER: str?
  PA_MASTODON_ACCESS_TOKEN: str?
  PA_TELEGRAM_BOTTOKEN: str?
  PA_TELEGRAM_CHATID: str?
  PA_EXCLUSIONS: str?
  PF_OPENAIP_LAYER: list(ON|OFF)?

ports:
  80/tcp: null
ports_description:
  80/tcp: Planefence web UI
